-- ====================================================================
-- 0004_building_fees.sql — richer building address + fee model
--   * country / postal_code on buildings
--   * fee method: fixed amount per apartment, or price per square meter
--   * apartment size (sqm) for per-meter billing
-- Building name is generated by the app as "<address>, <city>".
-- ====================================================================

CREATE TYPE fee_method AS ENUM ('fixed', 'per_sqm');

ALTER TABLE buildings
    ADD COLUMN country VARCHAR(100) NOT NULL DEFAULT 'ישראל',
    ADD COLUMN postal_code VARCHAR(20),
    ADD COLUMN fee_method fee_method NOT NULL DEFAULT 'fixed',
    ADD COLUMN fixed_monthly_fee NUMERIC(10, 2),
    ADD COLUMN price_per_sqm NUMERIC(10, 2);

ALTER TABLE apartments
    ADD COLUMN size_sqm NUMERIC(8, 2);

COMMENT ON COLUMN buildings.fee_method IS
    'fixed = every apartment pays fixed_monthly_fee; per_sqm = apartment pays size_sqm * price_per_sqm';
